/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleItem: typeof import('./src/components/ArticleItem.vue')['default'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    Footer: typeof import('./src/components/Footer.vue')['default'];
    Header: typeof import('./src/components/Header.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
